interiorID = GetInteriorAtCoords(483.2, 4810.5, -58.9)
	
	if IsValidInterior(interiorID) then
		EnableInteriorProp(interiorID, "set_int_02_decal_01")
		EnableInteriorProp(interiorID, "set_int_02_lounge1")
		EnableInteriorProp(interiorID, "set_int_02_cannon")
		EnableInteriorProp(interiorID, "set_int_02_clutter1")
		EnableInteriorProp(interiorID, "set_int_02_crewemblem")	
		EnableInteriorProp(interiorID, "set_int_02_shell")
		EnableInteriorProp(interiorID, "set_int_02_security")
		EnableInteriorProp(interiorID, "set_int_02_sleep")
		EnableInteriorProp(interiorID, "set_int_02_trophy1")
		EnableInteriorProp(interiorID, "set_int_02_paramedic_complete")
		EnableInteriorProp(interiorID, "set_Int_02_outfit_paramedic")
		EnableInteriorProp(interiorID, "set_Int_02_outfit_serverfarm")
		SetInteriorPropColor(interiorID, "set_int_02_decal_01", 1)
		SetInteriorPropColor(interiorID, "set_int_02_lounge1", 1)
		SetInteriorPropColor(interiorID, "set_int_02_cannon", 1)
		SetInteriorPropColor(interiorID, "set_int_02_clutter1", 1)
		SetInteriorPropColor(interiorID, "set_int_02_shell", 1)
		SetInteriorPropColor(interiorID, "set_int_02_security", 1)
		SetInteriorPropColor(interiorID, "set_int_02_sleep", 1)
		SetInteriorPropColor(interiorID, "set_int_02_trophy1", 1)
		SetInteriorPropColor(interiorID, "set_int_02_paramedic_complete", 1)
		SetInteriorPropColor(interiorID, "set_Int_02_outfit_paramedic", 1)
		SetInteriorPropColor(interiorID, "set_Int_02_outfit_serverfarm", 1)
		RefreshInterior(interiorID)
	end	